### ISSUE TITLE
Stole this

### ISSUE THREAD

**Issue by matthew4444** [ImagicalMine/pmt-source#1]

**Comment by keithkfng** [comment]
Idiot. It's open-source and free for anyone to use. Unlike you, bulling XenForo and stealing plugins. Learnt your lesson yet?

**Comment by keithkfng** [comment]
Idiot. It's open-source and free for anyone to use and upload to their web server. It's not like you nulling XenForo and stealing plugins. Learnt your lesson yet?

**Comment by matthew4444** [comment]
i didnt steal it,it wasnt my fourm so stop it

**Comment by keithkfng** [comment]
Yes you did, you uploaded the plugins.
